version: "1.0"
services:
  organization:
#    image: organization-service
    build: ./organizations-service
    ports:
      - "8083:8083"
    networks:
      - organization-user
      - organization-site
    depends_on:
      - user
      - site

  site:
#    image: site-service
    build: ./sites-service
    ports:
      - "8082:8082"
    networks:
      - site-user
      - organization-site
    depends_on:
      - user
 
  user:
#    image: user-service
    build: ./users-service
    ports:
      - "8081:8081"
    networks:
      - site-user
      - organization-user

networks:
  site-user:
  organization-user:
  organization-site:
